In [1]:
import numpy as np

In [14]:
arr = np.array([23,43,2,23,43,32,32,123,2432,4])

In [15]:
arr.shape

(10,)

In [16]:
# 1d to 2D

In [17]:
len(arr)

10

In [19]:
y=np.reshape(arr,(2,5))

In [20]:
y.shape

(2, 5)

In [21]:
y.ndim # To chck dimension 

2

In [25]:
ar = np.array([23,43,2,23,43,32,32,123,2432])

In [26]:
len(ar)

9

In [27]:
np.reshape(ar(3,3))

TypeError: 'numpy.ndarray' object is not callable

In [32]:
xx = np.array([23,43,2,23,43,32])

In [33]:
len(xx)

6

In [39]:
xy = np.reshape(xx,(-1,3))

In [40]:
xy

array([[23, 43,  2],
       [23, 43, 32]])

In [49]:
ab= ([21,32,43,22,23,453,5,34,7])


In [50]:
len(ab)

9

In [57]:
ba= np.reshape(ab,(-1))

In [58]:
ba


array([ 21,  32,  43,  22,  23, 453,   5,  34,   7])

In [59]:
# 2d to 1D

In [60]:
x = np.array([[1,2,2,3],[3,4,5,6]])

In [61]:
x

array([[1, 2, 2, 3],
       [3, 4, 5, 6]])

In [62]:
x.ndim

2

In [63]:
np.reshape(x,-1)

array([1, 2, 2, 3, 3, 4, 5, 6])

In [65]:
# flatten > Multi dim to 1 D 

In [66]:
# 3D to 1D

In [68]:
a= np.array([[[1,2,3,4]],[[4,5,6,7]],[[7,8,9,19]]])

In [69]:
a

array([[[ 1,  2,  3,  4]],

       [[ 4,  5,  6,  7]],

       [[ 7,  8,  9, 19]]])

In [70]:
a.flatten()

array([ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 19])

In [71]:
# 1D to 3D

In [74]:
zx= np.array([1,2,3,4,5,6,7,8,9,0,11,12,1,3,14,45,6,3])

In [75]:
len(zx)

18

In [76]:
np.reshape(zx,(3,3,2))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9,  0],
        [11, 12]],

       [[ 1,  3],
        [14, 45],
        [ 6,  3]]])

In [77]:
# Numpy- Random

#Python - Random

In [78]:
from numpy import random

In [81]:
# random helps to get and gnerate the data randomly

In [82]:
random.

In [ ]:
# Task to generate a series from 20 to 500

In [92]:
random.randint(122)   # it gives a number upto the given number always a random number

98

In [93]:
random.randint(50,100)

54

In [94]:
zx = random.randint(10,40,size = 6) # its for 1D
zx

array([23, 29, 11, 34, 15, 10])

In [95]:
# 2D 

In [97]:
random.randint(2,6, size = (3,4)) # For 2D

array([[3, 5, 4, 2],
       [2, 5, 3, 2],
       [3, 2, 2, 2]])

In [ ]:
# 3D

In [98]:
random.randint(2,6, size = (3,4, 4))  # for the 3D 

array([[[4, 5, 5, 2],
        [4, 3, 4, 3],
        [3, 3, 5, 2],
        [3, 5, 4, 2]],

       [[3, 4, 4, 4],
        [4, 5, 3, 5],
        [5, 2, 2, 3],
        [3, 3, 5, 5]],

       [[2, 3, 2, 2],
        [4, 4, 3, 5],
        [4, 2, 5, 2],
        [3, 5, 2, 5]]])

In [ ]:
# random.randint(start, end point, size/shape)

In [ ]:
random.rand()
# it generates the random element from the range of 0 to 1

In [99]:
random.rand()

0.744550535041172

In [101]:
random.rand(4)

array([0.93085604, 0.74339729, 0.53929598, 0.61666343])

In [102]:
random.rand(3,3)

array([[0.27977618, 0.35599627, 0.88224824],
       [0.14350728, 0.97058088, 0.1634121 ],
       [0.75877594, 0.67176961, 0.19866552]])

In [104]:
### Method - Choice

# in this we give the elemnts 

In [112]:
zx = random.choice([1,2,3,4,5,6,7,8])
-zx

7

In [114]:
zx

7

In [116]:
zx = random.choice([1,2,3,4,5,6,7,8,4,65,6,4,23,21,12,14,41,123,4,23,63,11,332,2], size = 5)
zx

array([41, 65,  3,  5,  4])

In [119]:
zx = random.choice([1,2,3,4,5,6,7,8,4,65,6,4,23,21,12,14,41,123,4,23,63,11,332,2], size = 3,2)
zx

SyntaxError: positional argument follows keyword argument (1471685479.py, line 1)

In [122]:
# help(random.gamma)

In [ ]:
d