In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({
    "Age" : [12,34,23,45,23,34,23,45,23],
    "Fav_color" : ["blue", "red", "green", "orange", "pink", "black", "pink", "blue", "blue"],
    "number" : [234345345,235456454,74564353,754678463,856345346,25464577458,8654654443,475745684534,4564574578]
})


In [3]:
df

Age Fav_color        number
0   12      blue     234345345
1   34       red     235456454
2   23     green      74564353
3   45    orange     754678463
4   23      pink     856345346
5   34     black   25464577458
6   23      pink    8654654443
7   45      blue  475745684534
8   23      blue    4564574578

In [4]:
# Encoding libraries
    #1) Label Encoding
    #2) Ordinal Encoding
    #3) One hot Encoding

In [5]:
df["Fav_color"].value_counts()

Fav_color
blue      3
pink      2
red       1
green     1
orange    1
black     1
Name: count, dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
lbl_encd = LabelEncoder()

In [8]:
df.head()

Age Fav_color     number
0   12      blue  234345345
1   34       red  235456454
2   23     green   74564353
3   45    orange  754678463
4   23      pink  856345346

In [9]:
df["Fav_color"] =lbl_encd.fit_transform(df["Fav_color"])
df

Age  Fav_color        number
0   12          1     234345345
1   34          5     235456454
2   23          2      74564353
3   45          3     754678463
4   23          4     856345346
5   34          0   25464577458
6   23          4    8654654443
7   45          1  475745684534
8   23          1    4564574578

In [10]:
transformed_color = lbl_encd.fit_transform(df["Fav_color"])
transformed_color

array([1, 5, 2, 3, 4, 0, 4, 1, 1], dtype=int64)

In [11]:
df

Age  Fav_color        number
0   12          1     234345345
1   34          5     235456454
2   23          2      74564353
3   45          3     754678463
4   23          4     856345346
5   34          0   25464577458
6   23          4    8654654443
7   45          1  475745684534
8   23          1    4564574578

In [12]:
df["Color_new"] = transformed_color   # This command is to add a new column in existing DF

In [13]:
df

Age  Fav_color        number  Color_new
0   12          1     234345345          1
1   34          5     235456454          5
2   23          2      74564353          2
3   45          3     754678463          3
4   23          4     856345346          4
5   34          0   25464577458          0
6   23          4    8654654443          4
7   45          1  475745684534          1
8   23          1    4564574578          1

In [14]:
# - - - - - - - - - - - - -  -  2  {ORDINAL ENCODING}- - - - - - - - - - - - - - - 

In [15]:
# It is similar as label Encoder  
# Changes are - in this we can directly assign the number 

In [16]:
df = pd.DataFrame({
    "Age" : [12,34,23,45,23,34,23,45,23],
    "Fav_color" : ["blue", "red", "green", "red", "pink", "black", "pink", "blue", "blue"],
    "number" : [234345345,235456454,74564353,754678463,856345346,25464577458,8654654443,475745684534,4564574578]
})

In [17]:
from sklearn.preprocessing import OrdinalEncoder

In [18]:
df["Fav_color"].value_counts()

Fav_color
blue     3
red      2
pink     2
green    1
black    1
Name: count, dtype: int64

In [19]:
Ord_enc = OrdinalEncoder(categories= [["red", "blue", "pink","green","black"]])

In [20]:
Ordinal_E = Ord_enc.fit_transform(df[["Fav_color"]])

In [37]:
Ordinal_E

array([[1.],
       [0.],
       [3.],
       [0.],
       [2.],
       [4.],
       [2.],
       [1.],
       [1.]])

In [21]:
df["Ord_Color"] = Ordinal_E
df

Age Fav_color        number  Ord_Color
0   12      blue     234345345        1.0
1   34       red     235456454        0.0
2   23     green      74564353        3.0
3   45       red     754678463        0.0
4   23      pink     856345346        2.0
5   34     black   25464577458        4.0
6   23      pink    8654654443        2.0
7   45      blue  475745684534        1.0
8   23      blue    4564574578        1.0

In [22]:
#  - - - - - - - - - - - - - - - - - 3) ONE HOT ENCODING  - - - - - - - - - - - - - - - - - - 

In [23]:
df = pd.DataFrame({
    "Age" : [12,34,23,45,23,34,23,45,23],
    "Fav_color" : ["blue", "red", "green", "red", "pink", "black", "pink", "blue", "blue"],
    "number" : [234345345,235456454,74564353,754678463,856345346,25464577458,8654654443,475745684534,4564574578]
})

In [24]:
df

Age Fav_color        number
0   12      blue     234345345
1   34       red     235456454
2   23     green      74564353
3   45       red     754678463
4   23      pink     856345346
5   34     black   25464577458
6   23      pink    8654654443
7   45      blue  475745684534
8   23      blue    4564574578

In [25]:
from sklearn.preprocessing import OneHotEncoder

In [26]:
ohe = OneHotEncoder()

In [27]:
OHE_color = ohe.fit_transform(df[["Fav_color"]])

In [28]:
OHE_color

<9x5 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [29]:
OHE_color.toarray()    # To convert sparse matrix into array format

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [30]:
df

Age Fav_color        number
0   12      blue     234345345
1   34       red     235456454
2   23     green      74564353
3   45       red     754678463
4   23      pink     856345346
5   34     black   25464577458
6   23      pink    8654654443
7   45      blue  475745684534
8   23      blue    4564574578

In [31]:
data = pd.DataFrame(OHE_color.toarray())    # to add values in DF

In [32]:
data

0    1    2    3    4
0  0.0  1.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  1.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  0.0  1.0
4  0.0  0.0  0.0  1.0  0.0
5  1.0  0.0  0.0  0.0  0.0
6  0.0  0.0  0.0  1.0  0.0
7  0.0  1.0  0.0  0.0  0.0
8  0.0  1.0  0.0  0.0  0.0

In [33]:
data = pd.DataFrame(OHE_color.toarray(), columns= ohe.get_feature_names_out(["Fav_color"]))   # To show which color is assign to which category

In [34]:
data

Fav_color_black  Fav_color_blue  Fav_color_green  Fav_color_pink  \
0              0.0             1.0              0.0             0.0   
1              0.0             0.0              0.0             0.0   
2              0.0             0.0              1.0             0.0   
3              0.0             0.0              0.0             0.0   
4              0.0             0.0              0.0             1.0   
5              1.0             0.0              0.0             0.0   
6              0.0             0.0              0.0             1.0   
7              0.0             1.0              0.0             0.0   
8              0.0             1.0              0.0             0.0   

   Fav_color_red  
0            0.0  
1            1.0  
2            0.0  
3            1.0  
4            0.0  
5            0.0  
6            0.0  
7            0.0  
8            0.0

In [35]:
xyz = pd.concat([df, data], axis= 1)   #To concatinate two data frames **************

In [36]:
xyz

Age Fav_color        number  Fav_color_black  Fav_color_blue  \
0   12      blue     234345345              0.0             1.0   
1   34       red     235456454              0.0             0.0   
2   23     green      74564353              0.0             0.0   
3   45       red     754678463              0.0             0.0   
4   23      pink     856345346              0.0             0.0   
5   34     black   25464577458              1.0             0.0   
6   23      pink    8654654443              0.0             0.0   
7   45      blue  475745684534              0.0             1.0   
8   23      blue    4564574578              0.0             1.0   

   Fav_color_green  Fav_color_pink  Fav_color_red  
0              0.0             0.0            0.0  
1              0.0             0.0            1.0  
2              1.0             0.0            0.0  
3              0.0             0.0            1.0  
4              0.0             1.0            0.0  
5              0.0             0.0            0.0  
6              0.0             1.0            0.0  
7              0.0             0.0            0.0  
8              0.0             0.0            0.0