In [2]:
import numpy as np

In [8]:
# 1D array aka Rector

a = np.array([1,2,3,4])
print (a)
print(type(a))


[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
# 2D aka Matrix

b = np.array([[1,2],[2,3]])
print(b)


[[1 2]
 [2 3]]


In [11]:
# 3D array aka Tensor

c= np.array([[[1,2],[2,3],[3,4],[4,5]]])
print(c)

[[[1 2]
  [2 3]
  [3 4]
  [4 5]]]


In [12]:
# to make a array of float value / bool and complex 

np.array ([1,2,2], dtype= float)

array([1., 2., 2.])

In [13]:
np.array ([1,2,2], dtype= bool)

array([ True,  True,  True])

In [14]:
np.array ([1,2,2], dtype= complex)

array([1.+0.j, 2.+0.j, 2.+0.j])

In [15]:
# Range function in numpy

np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
np.arange(1,12,2) # gives the gap of 2

array([ 1,  3,  5,  7,  9, 11])

In [21]:
#RESHAPE

np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
# np.arange(1,13).reshape(6,2)
# np.arange(1,13).reshape(12,1)
np.arange(1,13).reshape(2,6) # etc   product should be equal

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [25]:
# np.ones and np.zeros

# Use of np.ones ---> in DL part like in NLP 

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
np.random.random((3,5))  # we use 2 rnadom coz ---> random is a class and method name is also random

array([[0.26694569, 0.66215372, 0.76690496, 0.39649518, 0.94825233],
       [0.18521874, 0.27131485, 0.74166089, 0.4563031 , 0.53497661],
       [0.63363262, 0.32964865, 0.47225317, 0.59868376, 0.67233993]])

In [35]:
# np.linspace   #---> lower range, upper range , no.of items to generate
# Generates linealy seperateable points in a linear range

np.linspace(10,200,10)

array([ 10.        ,  31.11111111,  52.22222222,  73.33333333,
        94.44444444, 115.55555556, 136.66666667, 157.77777778,
       178.88888889, 200.        ])

In [41]:
# np.identity ---> Identity function helps to generate an identity matrix
# it have ones on the main digonal 0's all side.

a = np.identity(4)
# print (type(a))
print(a)

np.identity(6)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [55]:
# Attributes

# 1) ndim
# 2) shape
# 3) size
# 4) itemsize
# 5) dtype

a= np.arange(10)
b= np.arange(12, dtype= float).reshape(3,4)
c= np.arange(8).reshape(2,2,2)

# b.ndim

# 2) Shape

# a.shape
# b.shape
# c.shape


# 3) Size
# a.size
# b.size


# 4) itemsize

# a.itemsize
# b.itemsize
# c.itemsize

print(a.dtype)
print(c.dtype)
print(b.dtype)

int32
int32
float64


In [56]:
# Changing Dtype  -- > changing the file size to optimize memory or to save memory


c.astype(np.int16)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int16)

# Array Opertions

In [59]:
a = np.arange(12).reshape(3,4)
b= np.arange(12,24).reshape(3,4)

a

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [64]:
# 1) Scalar operation
# means operate with the single number like (a * 3) or (a + 4)

# a **3 
# a+4

# 2) Vetor operatoin

a**b

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]])

In [63]:
# relational operators

# b > 5
b==13

b<= 34

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [73]:
c = a**b
# print(c)

# print(np.max(c))
# print(np.min(c))

# to get the max and min on the axis, so the code will be 

# 0 ----> column and 1 -----> Row

np.max(c, axis = 0)
np.max(a, axis = 1)

np.prod(a, axis = 0)   # to get the product

array([  0,  45, 120, 231])

In [74]:
# mean / median / std / var
np.mean(b, axis = 1)

array([13.5, 17.5, 21.5])

In [75]:
np.median(a, axis = 0)

array([4., 5., 6., 7.])

In [78]:
np.std(a, axis =1)
np.std(a)


3.452052529534663

In [80]:
np.var(b)
np.var(b, axis = 1)

array([1.25, 1.25, 1.25])

In [82]:
# Dot product  --> goes with the same matrix like --- (3,4).(4,3)  ---> res- (3,3)
# or (12,4).(4,12)  and result will be (12, 12)

# ex

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12).reshape(4,3)

np.dot(a1,a2)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [84]:
# log and exponents function

np.log(a1)

np.exp(a1)

C:\Users\Farogh\AppData\Local\Temp\ipykernel_21928\4087939774.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

# round/ Floor/ Ceil functions

In [93]:
# round/ Floor/ Ceil functions

np.round
np.random.random((2,3))*100  # *100 for scalr values 
# np.round - round of the value at the nearest integer value, ex 5.6 > covert it to 6

np.round(np.random.random((2,3))*100 )

# np.floor - gives us the  round of the lesser nearest values, ex - 6.9 > convert it to 6

np.ceil(np.random.random((2,3))*100)  # incresing nearest value to the integer 

array([[72., 92., 31.],
       [41.,  2., 66.]])

In [104]:
np.random.random((3,4))

array([[0.39630646, 0.62161482, 0.67575138, 0.39913024],
       [0.77633851, 0.79592604, 0.94507047, 0.3472701 ],
       [0.62499491, 0.3594668 , 0.65789109, 0.94076779]])

In [101]:
np.random.randint(20, 100, size = (3, 3))

array([[59, 50, 27],
       [55, 92, 57],
       [77, 59, 36]])

In [109]:
np.random.random((2,3))

array([[0.55950101, 0.80477498, 0.35237246],
       [0.75677616, 0.85200346, 0.33707528]])

In [105]:
np.random.randint(10,20, size = (2,2))

array([[11, 12],
       [18, 17]])

# Indexing and Slicing

In [137]:
a = np.arange(10)
b = np.arange(12).reshape(3,4)  # (3,4) means 3 rows and 4 columns
c = np.arange(8).reshape(2,2,2)
d = np.arange(16).reshape(2,2,2,2)

# print(d)

In [130]:
print(a)
a[-1]

[0 1 2 3 4 5 6 7 8 9]


9

# Indexing

In [133]:
# --------For 2D array indexing------------
print(b)

print ("   ")

# to get particular element in 2D array
#syntax ---->  b[ row no. , column no] 

# searching for 6 
b[1, 2]

# serching to 11
b[2,3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
   


11

In [136]:
# For 3D Tensor

print(c)

# search element 5

# Syntax ----   c[array no, row no, columns no]

c[1,0,1]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


5

In [141]:
# For 4 D matrix
print(d)

# syntax - d[array no(3d), array no(2d), row no., column no]

# searching for element 13
# d[1,1,0,1]

# Searching for element 7
d[0,1,1,1]

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


7

# Slicing

In [147]:
# for 1D 

print (a)

# to get 2,3,4

a[2:5] #(start to n-1)

a[6:] # to get the element up to the last

a[2:7:2] #(start , end (n-1), gap/skip)

[0 1 2 3 4 5 6 7 8 9]


array([2, 4, 6])

In [190]:
# for 2D 
print(b)

# b[row no. , column no]
print ("  ")

# getting only 1st row
b[0,:]

# get [[5 6], [9 10]] 
# [row 1 :(onwards), column no 1 to 3(n-1) ]
b[1:, 1:3]

# get the[[2 3],[6 7],[10,11]]
# b[row 0 : (all), from column 2: (all)]
b[0: , 2:]


# get 0  3  8  11 ( all the corner no.)
# b[:(all rows), ]
b[::2,::3]

# get 1 3 9 11 
b[::2,1::2 ]

# get 4 and 7
# b[row 1, colomn no1 and skip 3 and last ]
b[1, 0::3]

# get [[1 2 3], [5 6 7]]
b[0:2, 1:]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
  


array([[1, 2, 3],
       [5, 6, 7]])

In [192]:
# b.iloc[1:3, :3]


In [193]:
# for the 3D Tensor

c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [195]:
c= np.arange(27).reshape(3,3,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [210]:
# for the center array 
c[1]

# for the 1st and last array
c[::2]

# to get the 3 4 5
# c[0 th array: first row:  all columns]
c[0,1,:]

# get 12 13 14
c[1,1,:]

# get 10 13 16
# c[1 postion array , all rows : 1st postion column]
c[1, :, 1]

# get [[22 23], [25 26]]
# c[array no.2 , row from 1:, column from 1: ]
c[2, 1:, 1:]


# get [[0 2],[18 20]]

c[::2,0,  ::2]

array([[ 0,  2],
       [18, 20]])