In [1]:
# pip install tensorflow[and-cuda]

In [2]:
# pip install keras

In [3]:
import numpy as np
import pandas as pd

In [4]:
data = pd.read_csv("Churn_Modelling.csv")

In [5]:
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [6]:
data.drop(columns = ["RowNumber", "CustomerId","Surname"], inplace = True)

In [7]:
data

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [8]:
# Converting categorical data into numerical one
# with the help of pandas funcion get_dummies (similar with one hot encoder)

change = pd.get_dummies(data, columns = ["Geography", "Gender"],drop_first= True)  
change

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0                  1        101348.88       1              False   
1                  1        112542.58       0              False   
2                  0        113931.57       1              False   
3                  0         93826.63       0              False   
4                  1         79084.10       0              False   
...              ...              ...     ...                ...   
9995               0         96270.64       0              False   
9996               1        101699.77       0              False   
9997               1         42085.58       1              False   
9998               0         92888.52       1               True   
9999               0         38190.78       0              False   

      Geography_Spain  Gender_Male  
0               False        False  
1                True        False  
2               False        False  
3               False        False  
4                True        False  
...               ...          ...  
9995            False         True  
9996            False         True  
9997            False        False  
9998            False         True  
9999            False        False  

[10000 rows x 12 columns]

In [9]:
# Now we are changing the data type of the newly generated data

new_data = change.astype(int)
new_data

CreditScore  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0             619   42       2        0              1          1   
1             608   41       1    83807              1          0   
2             502   42       8   159660              3          1   
3             699   39       1        0              2          0   
4             850   43       2   125510              1          1   
...           ...  ...     ...      ...            ...        ...   
9995          771   39       5        0              2          1   
9996          516   35      10    57369              1          1   
9997          709   36       7        0              1          0   
9998          772   42       3    75075              2          1   
9999          792   28       4   130142              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0                  1           101348       1                  0   
1                  1           112542       0                  0   
2                  0           113931       1                  0   
3                  0            93826       0                  0   
4                  1            79084       0                  0   
...              ...              ...     ...                ...   
9995               0            96270       0                  0   
9996               1           101699       0                  0   
9997               1            42085       1                  0   
9998               0            92888       1                  1   
9999               0            38190       0                  0   

      Geography_Spain  Gender_Male  
0                   0            0  
1                   1            0  
2                   0            0  
3                   0            0  
4                   1            0  
...               ...          ...  
9995                0            1  
9996                0            1  
9997                0            0  
9998                0            1  
9999                0            0  

[10000 rows x 12 columns]

In [10]:
# Seprating data

x = new_data.drop(columns = ["Exited"])
x

CreditScore  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0             619   42       2        0              1          1   
1             608   41       1    83807              1          0   
2             502   42       8   159660              3          1   
3             699   39       1        0              2          0   
4             850   43       2   125510              1          1   
...           ...  ...     ...      ...            ...        ...   
9995          771   39       5        0              2          1   
9996          516   35      10    57369              1          1   
9997          709   36       7        0              1          0   
9998          772   42       3    75075              2          1   
9999          792   28       4   130142              1          1   

      IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
0                  1           101348                  0                0   
1                  1           112542                  0                1   
2                  0           113931                  0                0   
3                  0            93826                  0                0   
4                  1            79084                  0                1   
...              ...              ...                ...              ...   
9995               0            96270                  0                0   
9996               1           101699                  0                0   
9997               1            42085                  0                0   
9998               0            92888                  1                0   
9999               0            38190                  0                0   

      Gender_Male  
0               0  
1               0  
2               0  
3               0  
4               0  
...           ...  
9995            1  
9996            1  
9997            0  
9998            1  
9999            0  

[10000 rows x 11 columns]

In [11]:
y = new_data["Exited"]
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int32

In [43]:
y[2]

1

In [12]:
# data spliting 

from sklearn.model_selection import train_test_split

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [14]:
x_train.shape

(8000, 11)

In [15]:
x_test.shape

(2000, 11)

In [16]:
y_test.shape

(2000,)

In [17]:
y_train.shape

(8000,)

In [18]:
# Norm alize the data (via Standard scaler)

from sklearn.preprocessing import StandardScaler

In [19]:
sc = StandardScaler()
sc

StandardScaler()

In [20]:
x_train_new = sc.fit_transform(x_train)
x_train_new

array([[-1.89035202e+00,  8.75681401e-01, -2.42140601e-03, ...,
        -5.71769086e-01, -5.74848406e-01, -1.10108555e+00],
       [ 6.85469812e-01, -1.31751515e+00,  6.89408883e-01, ...,
        -5.71769086e-01, -5.74848406e-01, -1.10108555e+00],
       [ 1.97310030e-01, -6.50020548e-01, -3.48336550e-01, ...,
         1.74895780e+00, -5.74848406e-01, -1.10108555e+00],
       ...,
       [ 6.33537920e-01,  3.83172893e+00, -2.42140601e-03, ...,
        -5.71769086e-01,  1.73958906e+00, -1.10108555e+00],
       [-3.11902942e-02, -1.22215878e+00,  1.38123917e+00, ...,
        -5.71769086e-01, -5.74848406e-01,  9.08194648e-01],
       [ 2.07696408e-01, -7.78823167e-02, -1.73199713e+00, ...,
        -5.71769086e-01,  1.73958906e+00,  9.08194648e-01]])

In [21]:
x_train_new[1]

array([ 0.68546981, -1.31751515,  0.68940888,  0.51166431,  0.8176719 ,
        0.64706357, -1.02788874,  1.5618744 , -0.57176909, -0.57484841,
       -1.10108555])

In [39]:
x_train_new[2]

array([ 0.19731003, -0.65002055, -0.34833655,  0.42038519,  0.8176719 ,
       -1.54544322,  0.97286794,  0.60565158,  1.7489578 , -0.57484841,
       -1.10108555])

In [22]:
x_test_new = sc.fit(x_test)
x_test_new

StandardScaler()

In [23]:
# !pip install tensorflow

In [24]:
# !pip install keras

In [25]:
# pip install setuptools
#

In [26]:
import tensorflow

from tensorflow import keras
from tensorflow.keras.optimizers import Adam

In [27]:
model  = tensorflow.keras.Sequential()
model

<Sequential name=sequential, built=False>

In [28]:
model.add(tensorflow.keras.layers.Dense(11, activation = 'sigmoid', input_dim = 11))  # activation = Softmax
model.add(tensorflow.keras.layers.Dense(11, activation = 'sigmoid'))
model.add(tensorflow.keras.layers.Dense(1, activation = 'sigmoid'))

C:\Users\Farogh\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [29]:
model

<Sequential name=sequential, built=True>

In [30]:
model.compile(optimizer = "Adam", loss = "binary_crossentropy", metrics = ["accuracy"])

In [31]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 11)                  │             132 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 11)                  │             132 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              12 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 276 (1.08 KB)

 Trainable params: 276 (1.08 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.fit(x_train_new, y_train, epochs =10)

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6020 - loss: 0.6328
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8027 - loss: 0.4788
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7997 - loss: 0.4628
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8044 - loss: 0.4367
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8086 - loss: 0.4239
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8155 - loss: 0.4271
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8179 - loss: 0.4200
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8282 - loss: 0.4024
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8290 - loss: 0.4067
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8263 - loss: 0.4081


In [33]:
y_pred = model.predict(x_train_new)
y_pred

250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


array([[0.4615054 ],
       [0.08142547],
       [0.11103472],
       ...,
       [0.5242064 ],
       [0.06827829],
       [0.13605621]], dtype=float32)

In [34]:
ab = np.array([[619,	42,	2,	0,	1,	1,	1,	101348,	0,	0,	0]])
model.predict(ab)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step


array([[0.10861018]], dtype=float32)

In [35]:
y_pred

array([[0.4615054 ],
       [0.08142547],
       [0.11103472],
       ...,
       [0.5242064 ],
       [0.06827829],
       [0.13605621]], dtype=float32)

In [38]:
xy = np.array([-1.12321696, -0.09327396,  1.03576227, -0.17218004, -0.90409742,
        0.65037001,  0.96365985, -0.55931511, -0.57850497, -0.57561821,
        0.90979992])

predic = model.predict(xy.reshape(1,-1))
print (predic)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
[[0.06296235]]


In [45]:
ab = np.array([ 0.19731003, -0.65002055, -0.34833655,  0.42038519,  0.8176719 ,
       -1.54544322,  0.97286794,  0.60565158,  1.7489578 , -0.57484841,
       -1.10108555])

model.predict(ab.reshape(1,-1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([[0.11103472]], dtype=float32)