In [1]:
import numpy as np

In [ ]:
np is faster then list as numpy stores data in a cont

In [3]:
lst = [12,3,23,34,23,23,5,23,33,94,53,54,39,65,44,4,234,6,546]
lst

[12, 3, 23, 34, 23, 23, 5, 23, 33, 94, 53, 54, 39, 65, 44, 4, 234, 6, 546]

In [24]:
arr = np.array(lst)
arr
sd = np.std(arr)
sd

123.17689911852098

In [9]:
# np.array([12,324,3,5,345,4,"Hello",34.3])


In [10]:

abc = arr*3
abc

array([  36,    9,   69,  102,   69,   69,   15,   69,   99,  282,  159,
        162,  117,  195,  132,   12,  702,   18, 1638])

In [25]:
arr = np.random.randint(90,100,size = 10)
arr

ab = np.random.randint(40,60, size = (2,2,2))
ab

mean = np.mean(arr)
mean

np.amax(arr)

median = np.median(arr)
median

# Standart Daviation
sd = np.std(arr)
sd

2.756809750418044

In [40]:
arr = np.random.randint(10,20,size = 20)
arr


# new = np.reshape(arr,(2,5))
# print(new)

new1 = np.reshape(arr,(2,10))
print(new1)

print ("   ")
new2 = arr.reshape(5,4)
print(new2)

[[12 12 14 12 10 14 12 11 14 17]
 [11 13 12 17 18 19 18 17 13 15]]
   
[[12 12 14 12]
 [10 14 12 11]
 [14 17 11 13]
 [12 17 18 19]
 [18 17 13 15]]
